services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\PaymentBundle\Controller\:
        resource: '../../Controller/*'

    c975L\PaymentBundle\Form\:
        resource: '../../Form/*'

    c975L\PaymentBundle\Security\:
        resource: '../../Security/*'
        bind:
            $roleNeeded: '%c975_l_payment.roleNeeded%'

    c975L\PaymentBundle\Service\:
        resource: '../../Service/*'

    c975L\PaymentBundle\Twig\:
        resource: '../../Twig/*'
