<?php

/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace c975L\PaymentBundle\Contract;

// Implemented, on top of BasketItemProviderInterface, by a provider whose items are picked from a catalogue the customer can go back to. Kept apart on purpose, like WeighableBasketItemProviderInterface: a provider selling a one-off payment link has no listing to return to, and this bundle knows of no shop to send anybody to - the catalogue is the selling bundle's own, and so is its address
interface CatalogueBasketItemProviderInterface
{
    // The address of the listing the "continue shopping" button goes back to, generated by the provider itself, which alone knows the parameters and the fragment its own listing takes
    // Null when the catalogue is not reachable for now - nothing on sale, the listing behind a closed shop - the button then not being drawn at all
    public function getCatalogueUrl(): ?string;
}
