services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\PaymentBundle\Controller\:
        resource: '../src/Controller/*'

    c975L\PaymentBundle\Form\:
        resource: '../src/Form/*'

    c975L\PaymentBundle\Security\:
        resource: '../src/Security/*'

    c975L\PaymentBundle\Service\:
        resource: '../src/Service/*'

    c975L\PaymentBundle\Twig\:
        resource: '../src/Twig/*'